import 'package:equatable/equatable.dart';
import 'package:survey_app_flutter/domain/entities/question_entity.dart';
import 'package:survey_app_flutter/domain/entities/survey_entity.dart';

/// Save lifecycle for survey creation/updating.
enum SurveySaveStatus {
  /// No save request in progress.
  initial,

  /// Save request in progress.
  saving,

  /// Save completed successfully.
  success,

  /// Save failed.
  failure,
}

/// This file contains the state classes for the SurveyBuilderBloc.
class SurveyBuilderState extends Equatable {
  /// The survey being edited, or null if creating a new survey.
  final SurveyEntity? survey;

  /// The current title of the survey in the builder.
  final String title;

  /// The current description of the survey in the builder.
  final String description;

  /// The current slug of the survey in the builder.
  final String slug;

  /// The current list of questions in the survey builder.
  final List<QuestionEntity> questions;

  /// Indicates whether the slug is auto-generated based on the title.
  final bool isSlugAutoGenerated;

  /// Current save lifecycle status.
  final SurveySaveStatus saveStatus;

  /// Optional save failure message.
  final String? saveErrorMessage;

  /// Creates a [SurveyBuilderState].
  const SurveyBuilderState({
    this.survey,
    this.title = '',
    this.description = '',
    this.slug = '',
    this.questions = const [],
    this.isSlugAutoGenerated = true,
    this.saveStatus = SurveySaveStatus.initial,
    this.saveErrorMessage,
  });

  /// Creates a copy of the current state with optional new values.
  SurveyBuilderState copyWith({
    SurveyEntity? survey,
    String? title,
    String? description,
    String? slug,
    List<QuestionEntity>? questions,
    bool? isSlugAutoGenerated,
    SurveySaveStatus? saveStatus,
    String? saveErrorMessage,
  }) {
    return SurveyBuilderState(
      survey: survey ?? this.survey,
      title: title ?? this.title,
      description: description ?? this.description,
      slug: slug ?? this.slug,
      questions: questions ?? this.questions,
      isSlugAutoGenerated: isSlugAutoGenerated ?? this.isSlugAutoGenerated,
      saveStatus: saveStatus ?? this.saveStatus,
      saveErrorMessage: saveErrorMessage ?? this.saveErrorMessage,
    );
  }

  /// Creates a copy with optional nullification flags.
  SurveyBuilderState copyWithNull({bool nullSaveErrorMessage = false}) {
    return SurveyBuilderState(
      survey: survey,
      title: title,
      description: description,
      slug: slug,
      questions: questions,
      isSlugAutoGenerated: isSlugAutoGenerated,
      saveStatus: saveStatus,
      saveErrorMessage: nullSaveErrorMessage ? null : saveErrorMessage,
    );
  }

  @override
  List<Object?> get props => [
    survey,
    title,
    description,
    slug,
    questions,
    isSlugAutoGenerated,
    saveStatus,
    saveErrorMessage,
  ];
}
