import 'package:equatable/equatable.dart';
import 'package:survey_app_flutter/domain/entities/question_entity.dart';
import 'package:survey_app_flutter/domain/entities/survey_entity.dart';

/// This file contains the state classes for the SurveyBuilderBloc.
class SurveyBuilderState extends Equatable {
  /// The survey being edited, or null if creating a new survey.
  final SurveyEntity? survey;

  /// The current title of the survey in the builder.
  final String title;

  /// The current description of the survey in the builder.
  final String description;

  /// The current slug of the survey in the builder.
  final String slug;

  /// The current list of questions in the survey builder.
  final List<QuestionEntity> questions;

  /// Indicates whether the slug is auto-generated based on the title.
  final bool isSlugAutoGenerated;

  /// Creates a [SurveyBuilderState].
  const SurveyBuilderState({
    this.survey,
    this.title = '',
    this.description = '',
    this.slug = '',
    this.questions = const [],
    this.isSlugAutoGenerated = true,
  });

  /// Creates a copy of the current state with optional new values.
  SurveyBuilderState copyWith({
    SurveyEntity? survey,
    String? title,
    String? description,
    String? slug,
    List<QuestionEntity>? questions,
    bool? isSlugAutoGenerated,
  }) {
    return SurveyBuilderState(
      survey: survey ?? this.survey,
      title: title ?? this.title,
      description: description ?? this.description,
      slug: slug ?? this.slug,
      questions: questions ?? this.questions,
      isSlugAutoGenerated: isSlugAutoGenerated ?? this.isSlugAutoGenerated,
    );
  }

  @override
  List<Object?> get props => [
    survey,
    title,
    description,
    slug,
    questions,
    isSlugAutoGenerated,
  ];
}
