import 'package:bloc/bloc.dart';
import 'package:survey_app_flutter/data/entities_impl/survey_entity_impl.dart';
import 'package:survey_app_flutter/domain/entities/question_entity.dart';
import 'package:survey_app_flutter/domain/entities/survey_entity.dart';
import 'package:survey_app_flutter/domain/use_cases/survey_use_case.dart';
import 'package:survey_app_flutter/domain/use_cases/user_use_case.dart';
import 'package:survey_app_flutter/presentation/survey_builder/bloc/survey_builder_event.dart';
import 'package:survey_app_flutter/presentation/survey_builder/bloc/survey_builder_state.dart';

/// Bloc for managing the state of the survey builder page.
class SurveyBuilderBloc extends Bloc<SurveyBuilderEvent, SurveyBuilderState> {
  final SurveyUseCase _surveyUseCase;
  final UserUseCase _userUseCase;

  /// Constructs a [SurveyBuilderBloc] with the initial state
  /// of [SurveyBuilderState].
  SurveyBuilderBloc(this._surveyUseCase, this._userUseCase)
    : super(const SurveyBuilderState()) {
    on<LoadSurveyForEditing>(_onLoadSurveyForEditing);

    on<UpdateSurveyTitle>(_onUpdateSurveyTitle);
    on<UpdateSurveyDescription>(_onUpdateSurveyDescription);
    on<UpdateSurveySlug>(_onUpdateSurveySlug);

    on<EditQuestion>(_onEditQuestion);
    on<AddQuestion>(_onAddQuestion);
    on<RemoveQuestion>(_onRemoveQuestion);
    on<ReorderQuestions>(_onReorderQuestions);

    on<SaveSurvey>(_onSaveSurvey);
    on<ResetSurveySaveStatus>(_onResetSurveySaveStatus);
    on<ResetSurveyBuilder>(_onResetSurveyBuilder);
  }

  void _onLoadSurveyForEditing(
    LoadSurveyForEditing event,
    Emitter<SurveyBuilderState> emit,
  ) {
    final survey = event.survey;
    emit(
      state.copyWith(
        survey: survey,
        title: survey.title,
        description: survey.description,
        slug: survey.slug,
        questions: survey.questions,
      ),
    );
  }

  void _onUpdateSurveyTitle(
    UpdateSurveyTitle event,
    Emitter<SurveyBuilderState> emit,
  ) {
    emit(state.copyWith(title: event.title));
    add(UpdateSurveySlug(null));
  }

  void _onUpdateSurveyDescription(
    UpdateSurveyDescription event,
    Emitter<SurveyBuilderState> emit,
  ) {
    emit(state.copyWith(description: event.description));
  }

  void _onUpdateSurveySlug(
    UpdateSurveySlug event,
    Emitter<SurveyBuilderState> emit,
  ) {
    if ((event.slug == null || event.slug!.isEmpty) &&
        state.isSlugAutoGenerated) {
      final generatedSlug = _generateSlug(state.title);
      emit(state.copyWith(slug: generatedSlug));
      return;
    }
    emit(state.copyWith(slug: event.slug, isSlugAutoGenerated: false));
  }

  void _onEditQuestion(
    EditQuestion event,
    Emitter<SurveyBuilderState> emit,
  ) {
    final question = event.question;
    final updatedQuestions = state.questions.map((q) {
      if (q.order == question.order) {
        return question;
      }
      return q;
    }).toList();

    emit(state.copyWith(questions: updatedQuestions));
  }

  void _onAddQuestion(
    AddQuestion event,
    Emitter<SurveyBuilderState> emit,
  ) {
    final updatedQuestions = List<QuestionEntity>.from(state.questions)
      ..add(event.question);
    emit(state.copyWith(questions: updatedQuestions));
  }

  void _onRemoveQuestion(
    RemoveQuestion event,
    Emitter<SurveyBuilderState> emit,
  ) {
    final updatedQuestions = List<QuestionEntity>.from(state.questions)
      ..removeWhere((q) => q.order == event.orderNumber);
    emit(state.copyWith(questions: updatedQuestions));
  }

  void _onReorderQuestions(
    ReorderQuestions event,
    Emitter<SurveyBuilderState> emit,
  ) {
    final updatedQuestions = List<QuestionEntity>.from(state.questions);

    if (event.oldIndex < 0 || event.oldIndex >= updatedQuestions.length) {
      return;
    }

    if (event.newIndex < 0 || event.newIndex >= updatedQuestions.length) {
      return;
    }

    final item = updatedQuestions.removeAt(event.oldIndex);
    updatedQuestions.insert(event.newIndex, item);

    final reindexedQuestions = updatedQuestions
        .asMap()
        .entries
        .map((entry) => entry.value.copyWith(order: entry.key + 1))
        .toList();

    emit(state.copyWith(questions: reindexedQuestions));
  }

  Future<void> _onSaveSurvey(
    SaveSurvey event,
    Emitter<SurveyBuilderState> emit,
  ) async {
    final hasRequiredFields =
        state.title.trim().isNotEmpty &&
        state.description.trim().isNotEmpty &&
        state.slug.trim().isNotEmpty;
    final hasAtLeastOneQuestion = state.questions.isNotEmpty;

    if (!hasRequiredFields || !hasAtLeastOneQuestion) {
      return;
    }

    emit(
      state
          .copyWith(saveStatus: SurveySaveStatus.saving)
          .copyWithNull(nullSaveErrorMessage: true),
    );

    try {
      final token = await _userUseCase.getAuthToken();
      if (token == null || token.isEmpty) {
        throw Exception('No auth token available.');
      }

      if (state.survey == null) {
        final createdSurvey = await _surveyUseCase.createSurvey(
          token: token,
          ownerId: event.ownerId,
          title: state.title,
          description: state.description,
          slug: state.slug,
          status: SurveyStatus.draft,
        );

        try {
          for (final question in state.questions) {
            await _surveyUseCase.createQuestion(
              surveyId: createdSurvey.id,
              token: token,
              type: question.type,
              title: question.title,
              required: question.required,
              order: question.order,
              maxLength: question.maxLength,
              maxSelections: question.maxSelections,
              options: question.options,
            );
          }
        } catch (e) {
          await _surveyUseCase.deleteSurvey(
            token: token,
            surveyId: createdSurvey.id,
          );
          throw Exception(
            'Failed to add questions. Created survey was rolled back. $e',
          );
        }

        if (event.status == SurveyStatus.published) {
          await _surveyUseCase.publishSurvey(
            token: token,
            surveyId: createdSurvey.id,
          );
        }

        emit(
          state
              .copyWith(
                survey: createdSurvey,
                saveStatus: SurveySaveStatus.success,
              )
              .copyWithNull(nullSaveErrorMessage: true),
        );
      } else {
        final currentSurvey = state.survey!;
        final updatedSurvey = SurveyEntityImpl(
          id: currentSurvey.id,
          ownerId: currentSurvey.ownerId,
          slug: state.slug,
          title: state.title,
          description: state.description,
          status: SurveyStatus.draft,
          createdAt: currentSurvey.createdAt,
          publishedAt: currentSurvey.publishedAt,
          closedAt: currentSurvey.closedAt,
          questions: state.questions,
        );

        final savedSurvey = await _surveyUseCase.updateSurvey(
          token,
          updatedSurvey,
        );

        final previousQuestionIds = currentSurvey.questions
            .map((q) => q.id)
            .where((id) => id.isNotEmpty)
            .toSet();
        final currentQuestionIds = state.questions
            .map((q) => q.id)
            .where((id) => id.isNotEmpty)
            .toSet();

        final removedQuestionIds = previousQuestionIds.where(
          (id) => !currentQuestionIds.contains(id),
        );

        for (final questionId in removedQuestionIds) {
          await _surveyUseCase.deleteQuestion(
            token: token,
            surveyId: savedSurvey.id,
            questionId: questionId,
          );
        }

        for (final question in state.questions) {
          if (question.id.isEmpty) {
            await _surveyUseCase.createQuestion(
              surveyId: savedSurvey.id,
              token: token,
              type: question.type,
              title: question.title,
              required: question.required,
              order: question.order,
              maxLength: question.maxLength,
              maxSelections: question.maxSelections,
              options: question.options,
            );
          } else {
            await _surveyUseCase.updateQuestion(
              token,
              question,
              savedSurvey.id,
            );
          }
        }

        if (event.status == SurveyStatus.published) {
          await _surveyUseCase.publishSurvey(
            token: token,
            surveyId: savedSurvey.id,
          );
        }

        emit(
          state
              .copyWith(
                survey: savedSurvey,
                saveStatus: SurveySaveStatus.success,
              )
              .copyWithNull(nullSaveErrorMessage: true),
        );
      }
    } catch (e) {
      emit(
        state.copyWith(
          saveStatus: SurveySaveStatus.failure,
          saveErrorMessage: e.toString(),
        ),
      );
    }
  }

  void _onResetSurveySaveStatus(
    ResetSurveySaveStatus event,
    Emitter<SurveyBuilderState> emit,
  ) {
    emit(
      state
          .copyWith(saveStatus: SurveySaveStatus.initial)
          .copyWithNull(nullSaveErrorMessage: true),
    );
  }

  void _onResetSurveyBuilder(
    ResetSurveyBuilder event,
    Emitter<SurveyBuilderState> emit,
  ) {
    emit(const SurveyBuilderState());
  }

  String _generateSlug(String input) {
    return input
        .toLowerCase()
        .trim()
        .replaceAll(RegExp(r'[^\w\s-]'), '')
        .replaceAll(RegExp(r'\s+'), '-')
        .replaceAll(RegExp('-+'), '-');
  }
}
