import 'package:bloc/bloc.dart';
import 'package:survey_app_flutter/domain/entities/question_entity.dart';
import 'package:survey_app_flutter/domain/use_cases/survey_use_case.dart';
import 'package:survey_app_flutter/presentation/survey_builder/bloc/survey_builder_event.dart';
import 'package:survey_app_flutter/presentation/survey_builder/bloc/survey_builder_state.dart';

/// Bloc for managing the state of the survey builder page.
class SurveyBuilderBloc extends Bloc<SurveyBuilderEvent, SurveyBuilderState> {
  final SurveyUseCase _surveyUseCase;

  /// Constructs a [SurveyBuilderBloc] with the initial state
  /// of [SurveyBuilderState].
  SurveyBuilderBloc(this._surveyUseCase) : super(const SurveyBuilderState()) {
    on<LoadSurveyForEditing>(_onLoadSurveyForEditing);

    on<UpdateSurveyTitle>(_onUpdateSurveyTitle);
    on<UpdateSurveyDescription>(_onUpdateSurveyDescription);
    on<UpdateSurveySlug>(_onUpdateSurveySlug);

    on<AddQuestion>(_onAddQuestion);
    on<RemoveQuestion>(_onRemoveQuestion);

    on<SaveSurvey>(_onSaveSurvey);
  }

  void _onLoadSurveyForEditing(
    LoadSurveyForEditing event,
    Emitter<SurveyBuilderState> emit,
  ) {
    final survey = event.survey;
    emit(
      state.copyWith(
        survey: survey,
        title: survey.title,
        description: survey.description,
        slug: survey.slug,
        questions: survey.questions,
      ),
    );
  }

  void _onUpdateSurveyTitle(
    UpdateSurveyTitle event,
    Emitter<SurveyBuilderState> emit,
  ) {
    emit(state.copyWith(title: event.title));
    add(UpdateSurveySlug(null));
  }

  void _onUpdateSurveyDescription(
    UpdateSurveyDescription event,
    Emitter<SurveyBuilderState> emit,
  ) {
    emit(state.copyWith(description: event.description));
  }

  void _onUpdateSurveySlug(
    UpdateSurveySlug event,
    Emitter<SurveyBuilderState> emit,
  ) {
    if ((event.slug == null || event.slug!.isEmpty) &&
        state.isSlugAutoGenerated) {
      final generatedSlug = _generateSlug(state.title);
      emit(state.copyWith(slug: generatedSlug));
      return;
    }
    emit(state.copyWith(slug: event.slug, isSlugAutoGenerated: false));
  }

  void _onAddQuestion(
    AddQuestion event,
    Emitter<SurveyBuilderState> emit,
  ) {
    final updatedQuestions = List<QuestionEntity>.from(state.questions)
      ..add(event.question);
    emit(state.copyWith(questions: updatedQuestions));
  }

  void _onRemoveQuestion(
    RemoveQuestion event,
    Emitter<SurveyBuilderState> emit,
  ) {
    final updatedQuestions = List<QuestionEntity>.from(state.questions)
      ..removeWhere((q) => q.id == event.questionId);
    emit(state.copyWith(questions: updatedQuestions));
  }

  void _onSaveSurvey(
    SaveSurvey event,
    Emitter<SurveyBuilderState> emit,
  ) {
    if (state.survey == null) {
      _surveyUseCase.createSurvey(
        ownerId: event.ownerId,
        title: state.title,
        description: state.description,
        slug: state.slug,
        status: event.status,
      );
    } else {
      // Handle updating an existing survey
    }
  }

  String _generateSlug(String input) {
    return input
        .toLowerCase()
        .trim()
        .replaceAll(RegExp(r'[^\w\s-]'), '')
        .replaceAll(RegExp(r'\s+'), '-')
        .replaceAll(RegExp('-+'), '-');
  }
}
