import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:survey_app_flutter/domain/entities/survey_entity.dart';
import 'package:survey_app_flutter/presentation/admin/bloc/admin_event.dart';
import 'package:survey_app_flutter/presentation/survey_builder/bloc/survey_builder_bloc.dart';
import 'package:survey_app_flutter/presentation/survey_builder/bloc/survey_builder_event.dart';
import 'package:survey_app_flutter/presentation/survey_builder/bloc/survey_builder_state.dart';
import 'package:survey_app_flutter/shared/custom_button.dart';
import 'package:survey_app_flutter/shared/custom_color_variant.dart';
import 'package:survey_app_flutter/shared/custom_textfield.dart';
import 'package:survey_app_flutter/utils/app_blocs.dart';
import 'package:survey_app_flutter/utils/app_strings.dart';

/// A widget that displays the details section of the survey builder page.
class SurveyBuilderDetailsSection extends StatelessWidget {
  /// Constructs a [SurveyBuilderDetailsSection].
  const SurveyBuilderDetailsSection({
    required this.surveyTitleController,
    required this.surveyDescriptionController,
    required this.surveySlugController,
    this.isReadOnly = false,
    super.key,
  });

  /// Controller for the survey title text field.
  final TextEditingController surveyTitleController;

  /// Controller for the survey description text field.
  final TextEditingController surveyDescriptionController;

  /// Controller for the survey slug text field.
  final TextEditingController surveySlugController;

  /// Whether details are read-only.
  final bool isReadOnly;

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;
    final textTheme = Theme.of(context).textTheme;
    return BlocListener<SurveyBuilderBloc, SurveyBuilderState>(
      bloc: AppBlocs.surveyBuilderBloc,
      listenWhen: (previous, current) =>
          previous.saveStatus != current.saveStatus,
      listener: (context, state) {
        if (state.saveStatus == SurveySaveStatus.success) {
          AppBlocs.adminBloc.add(const AdminSurveysRefreshed());
          AppBlocs.surveyBuilderBloc.add(ResetSurveySaveStatus());
          Navigator.of(context).pop();
        }

        if (state.saveStatus == SurveySaveStatus.failure) {
          final message = state.saveErrorMessage ?? 'Failed to save survey';
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text(message)),
          );
          AppBlocs.surveyBuilderBloc.add(ResetSurveySaveStatus());
        }
      },
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            AppStrings.surveyDetailsTitle.toUpperCase(),
            style: textTheme.titleMedium?.copyWith(
              color: colorScheme.onSurfaceVariant,
              fontWeight: FontWeight.w600,
            ),
          ),
          const SizedBox(height: 20),
          Text(
            AppStrings.surveyTitleLabel,
            style: textTheme.bodyMedium?.copyWith(
              color: colorScheme.onSurfaceVariant,
            ),
          ),
          const SizedBox(height: 8),
          CustomTextfield(
            hintText: AppStrings.surveyTitlePlaceholder,
            controller: surveyTitleController,
            readOnly: isReadOnly,
            onChanged: isReadOnly
                ? null
                : (value) {
                    AppBlocs.surveyBuilderBloc.add(UpdateSurveyTitle(value));
                  },
          ),
          const SizedBox(height: 16),
          Text(
            AppStrings.surveyDescriptionLabel,
            style: textTheme.bodyMedium?.copyWith(
              color: colorScheme.onSurfaceVariant,
            ),
          ),
          const SizedBox(height: 8),
          CustomTextfield(
            hintText: AppStrings.surveyDescriptionPlaceholder,
            controller: surveyDescriptionController,
            minLines: 3,
            maxLines: 3,
            readOnly: isReadOnly,
            onChanged: isReadOnly
                ? null
                : (value) {
                    AppBlocs.surveyBuilderBloc.add(
                      UpdateSurveyDescription(value),
                    );
                  },
          ),
          const SizedBox(height: 16),
          Text(
            AppStrings.surveySlugLabel,
            style: textTheme.bodyMedium?.copyWith(
              color: colorScheme.onSurfaceVariant,
            ),
          ),
          const SizedBox(height: 8),
          BlocListener<SurveyBuilderBloc, SurveyBuilderState>(
            listener: (context, state) {
              surveySlugController.text = state.slug;
            },
            listenWhen: (previous, current) =>
                previous.slug != current.slug && current.isSlugAutoGenerated,
            child: CustomTextfield(
              hintText: AppStrings.surveySlugPlaceholder,
              controller: surveySlugController,
              textColor: colorScheme.secondary,
              readOnly: isReadOnly,
              onChanged: isReadOnly
                  ? null
                  : (value) {
                      AppBlocs.surveyBuilderBloc.add(UpdateSurveySlug(value));
                    },
            ),
          ),
          const SizedBox(height: 8),
          Text(
            AppStrings.autoGenerateSlugHelperText,
            style: textTheme.bodySmall?.copyWith(
              color: colorScheme.onSurfaceVariant,
            ),
          ),
          const SizedBox(height: 20),
          if (!isReadOnly) ...[
            Divider(color: colorScheme.onSurfaceVariant),
            const SizedBox(height: 20),
            Text(
              AppStrings.actionsTitle.toUpperCase(),
              style: textTheme.titleMedium?.copyWith(
                color: colorScheme.onSurfaceVariant,
                fontWeight: FontWeight.w600,
              ),
            ),
            const SizedBox(height: 12),
            BlocBuilder<SurveyBuilderBloc, SurveyBuilderState>(
              bloc: AppBlocs.surveyBuilderBloc,
              buildWhen: (previous, current) =>
                  previous.title != current.title ||
                  previous.description != current.description ||
                  previous.slug != current.slug ||
                  previous.questions != current.questions,
              builder: (context, state) {
                final hasRequiredFields =
                    state.title.trim().isNotEmpty &&
                    state.description.trim().isNotEmpty &&
                    state.slug.trim().isNotEmpty;
                final hasAtLeastOneQuestion = state.questions.isNotEmpty;
                final canCreateSurvey =
                    hasRequiredFields && hasAtLeastOneQuestion;

                String? validationMessage;
                if (!hasRequiredFields) {
                  validationMessage =
                      AppStrings.surveyBuilderInvalidFieldsMessage;
                } else if (!hasAtLeastOneQuestion) {
                  validationMessage =
                      AppStrings.surveyBuilderMissingQuestionsMessage;
                }

                return Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    if (validationMessage != null)
                      Padding(
                        padding: const EdgeInsets.only(bottom: 12),
                        child: Text(
                          validationMessage,
                          style: textTheme.bodySmall?.copyWith(
                            color: colorScheme.error,
                          ),
                        ),
                      ),
                    SizedBox(
                      width: double.infinity,
                      child: CustomButton(
                        onPressed: canCreateSurvey
                            ? () {
                                AppBlocs.surveyBuilderBloc.add(
                                  SaveSurvey(
                                    SurveyStatus.draft,
                                    AppBlocs.adminBloc.state.adminUser?.id ??
                                        '',
                                  ),
                                );
                              }
                            : null,
                        text: '💾   ${AppStrings.saveSurveyButton}',
                      ),
                    ),
                    const SizedBox(height: 12),
                    SizedBox(
                      width: double.infinity,
                      child: CustomButton(
                        onPressed: canCreateSurvey
                            ? () {
                                AppBlocs.surveyBuilderBloc.add(
                                  SaveSurvey(
                                    SurveyStatus.published,
                                    AppBlocs.adminBloc.state.adminUser?.id ??
                                        '',
                                  ),
                                );
                              }
                            : null,
                        text: '🚀   ${AppStrings.publishSurveyButton}',
                        variant: CustomColorVariant.primary,
                      ),
                    ),
                  ],
                );
              },
            ),
          ],
        ],
      ),
    );
  }
}
