plugins:
  solid_lints:
    path: D:/Coding/Flutter/solid_lints

    diagnostics:
      avoid_global_state: true

      avoid_debug_print_in_release:
        enabled: true
        max_occurrences: 0
        allow_in_tests: true

      max_function_length:
        enabled: true
        max_lines: 50
        ignore_private: true

      prefer_single_quotes: true